[package]
name = "clipboard-import"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aes.workspace = true
blake3.workspace = true
cap-fs-ext.workspace = true
cap-std.workspace = true
cbc.workspace = true
chrono.workspace = true
clipboard-core = { path = "../clipboard-core" }
clipboard-store = { path = "../clipboard-store" }
csv-core.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
allocation-counter.workspace = true
tempfile.workspace = true
