//! Which pasteboard items must never be recorded.
//!
//! macOS has no enforcement here, only a convention: an application that puts
//! something short-lived or secret on the pasteboard adds a marker type asking
//! everyone else to leave it alone. Password managers rely on it. Honouring it
//! is the difference between a history and a leak, so the decision is taken
//! from the type list alone, before any payload is read.

/// The item is meant to vanish; nobody should keep it.
pub const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
/// The item is a secret — a password manager put it there.
pub const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
/// The item was produced by software rather than by a person copying.
pub const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";
/// The application that produced the item, when it chose to say so.
pub const SOURCE_TYPE: &str = "org.nspasteboard.source";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MarkerPolicy {
    /// Nothing objected; the item may be read and recorded.
    Accept,
    RejectTransient,
    RejectConcealed,
    RejectAutoGenerated,
}

impl MarkerPolicy {
    pub fn is_rejected(self) -> bool {
        !matches!(self, Self::Accept)
    }

    /// The stable code recorded when an item is turned away. Never a sentence,
    /// and never anything derived from the payload.
    pub fn reason(self) -> Option<&'static str> {
        match self {
            Self::Accept => None,
            Self::RejectTransient => Some("transient"),
            Self::RejectConcealed => Some("concealed"),
            Self::RejectAutoGenerated => Some("auto_generated"),
        }
    }
}

/// Decides from the advertised types alone.
///
/// Concealed outranks transient: if an item is both, the reason worth recording
/// is that it was a secret.
pub fn classify_types<S: AsRef<str>>(types: &[S]) -> MarkerPolicy {
    let has = |marker: &str| types.iter().any(|value| value.as_ref() == marker);
    if has(CONCEALED_TYPE) {
        return MarkerPolicy::RejectConcealed;
    }
    if has(TRANSIENT_TYPE) {
        return MarkerPolicy::RejectTransient;
    }
    if has(AUTO_GENERATED_TYPE) {
        return MarkerPolicy::RejectAutoGenerated;
    }
    MarkerPolicy::Accept
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_plain_text_item_is_accepted() {
        assert_eq!(
            classify_types(&["public.utf8-plain-text"]),
            MarkerPolicy::Accept
        );
    }

    #[test]
    fn transient_and_concealed_items_are_never_captured() {
        assert_eq!(
            classify_types(&["public.utf8-plain-text", TRANSIENT_TYPE]),
            MarkerPolicy::RejectTransient
        );
        assert_eq!(
            classify_types(&[CONCEALED_TYPE]),
            MarkerPolicy::RejectConcealed
        );
        assert_eq!(
            classify_types(&["public.utf8-plain-text", AUTO_GENERATED_TYPE]),
            MarkerPolicy::RejectAutoGenerated
        );
    }

    #[test]
    fn a_secret_that_is_also_transient_is_reported_as_a_secret() {
        assert_eq!(
            classify_types(&[TRANSIENT_TYPE, CONCEALED_TYPE]),
            MarkerPolicy::RejectConcealed
        );
    }

    #[test]
    fn every_rejection_carries_a_stable_reason_and_acceptance_carries_none() {
        assert_eq!(MarkerPolicy::Accept.reason(), None);
        assert_eq!(MarkerPolicy::RejectTransient.reason(), Some("transient"));
        assert_eq!(MarkerPolicy::RejectConcealed.reason(), Some("concealed"));
        assert_eq!(
            MarkerPolicy::RejectAutoGenerated.reason(),
            Some("auto_generated")
        );
        assert!(MarkerPolicy::RejectConcealed.is_rejected());
        assert!(!MarkerPolicy::Accept.is_rejected());
    }
}
